Repository westpa/westpa, pull requests merged in 2024-04, with the labels that each got.

#394 Include short description for package on PyPI page
  setup.py
Labels: enhancement

#395 W_succ ignores -W argument
  src/westpa/oldtools/aframe/data_reader.py
Labels: bug

#398 hotfix for propagator
  src/westpa/core/propagators/executable.py
  src/westpa/core/states.py
  src/westpa/core/trajectory.py
  tests/test_states.py
Labels: bug

#402 force x86-64 macos GitHub Action Runners
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  src/westpa/core/sim_manager.py
  src/westpa/westext/hamsm_restarting/restart_driver.py
Labels: CI maintenance

#405 Add support for testing and wheel-building on macos-arm64 (Apple Silicon)
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: CI maintenance

#407 Swapping CI env to install mdtraj with conda
  devtools/conda-envs/test_env.yaml
Labels: CI maintenance

#403 Mab lite with direction 86
  src/westpa/core/binning/mab.py
  src/westpa/core/binning/mab_manager.py
Labels: enhancement

#408 allow users to specify executable config in west.data.datasets
  src/westpa/core/propagators/executable.py
  tests/conftest.py
  tests/refs/west_executable.cfg
  tests/test_executable.py
  tests/test_loaders.py
Labels: enhancement
