Repository westpa/westpa, pull requests merged in 2024-09, with the labels that each got.

#443 remove w_fluxanl deprecation warning
  src/westpa/cli/tools/w_fluxanl.py
Labels: Error Messages Improvement

#436 Fixing the MAB skip function in 2+ dimensions.
  src/westpa/core/binning/mab.py
  tests/refs/mab_assignments_ref.h5
  tests/test_binning.py
Labels: bug, enhancement, CI maintenance

#446 Allow reruns on fluxanl test
  tests/test_tools/common.py
  tests/test_tools/test_w_fluxanl.py
Labels: CI maintenance

#445 Clean up new MAB tests
  tests/conftest.py
  tests/refs/mab_assignments_ref.h5
  tests/test_binning.py
Labels: CI maintenance
